version: '3'
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: deepadmin
      POSTGRES_PASSWORD: temp
      POSTGRES_MULTIPLE_DATABASES: deepq,deepadmin:deepq_shadow,deepadmin
    volumes:
      - ./deploy/local/docker/postgres/init-script:/docker-entrypoint-initdb.d
      - postgres:/var/lib/postgresql/data
    ports:
      - "5433:5432"
volumes:
  postgres:
