version: '3.10'
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: deepadmin
      POSTGRES_PASSWORD: temp
      POSTGRES_MULTIPLE_DATABASES: deepq,deepadmin:deepq_shadow,deepadmin
    volumes:
      - ./deploy/local/docker/postgres/init-script:/docker-entrypoint-initdb.d
      - postgres:/var/lib/postgresql/data
    ports:
      - "5433:5432"
  rabbitmq:
    image: rabbitmq:3-management
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    ports:
        - 5672:5672
        - 15672:15672
  redis:
    image: redis
    ports:
      - 6379:6379
    volumes:
      - redis:/data
  bullboard:
    image: addono/bull-board
    ports:
      - 6380:3000
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_USE_TLS: 'false'
      BULL_PREFIX: bull
    depends_on:
      - redis
volumes:
  postgres:
  redis:
